[package]
authors = ["Vladislav Vasilev <vfaust.thefuture@gmail.com>"]
description = "Drop Helpers"
edition = "2021"
name = "drop-helper-contracts-helpers"
version = "1.0.0"

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
neutron-sdk = { workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
cw-ownable = { workspace = true }