[package]
authors = ["Vladislav Vasilev <vfaust.thefuture@gmail.com>"]
description = "Package for shared+separated msg, state and error contract pieces"
edition = "2021"
name = "drop-helper-contracts-base"
version = "0.1.0"

exclude = [
    "contract.wasm",
    "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
cw-utils = { workspace = true }